Refactor/EV-784/[FLUTTER] 03 - Componetização
FelipeBortoliniWarren/CryptoCardsEverest pull request #2
Opened 2022-09-14 13:04 UTC by FelipeBortoliniWarren

### Descrição

Componentização do código, extraindo os principais widgets em pastas com a estruturação de Clean Architecture e Clean Code.

Bônus: Internacionalização (inglês e português).

### Links
[figma](https://www.figma.com/file/aB3rbJ4RaCxBnG3SOCalgQ/Desafio-de-Flutter?node-id=2749%3A24117)

[card](https://warren.atlassian.net/jira/software/c/projects/EV/boards/454?modal=detail&selectedIssue=EV-784)

### Screenshots

- Organização de pastas:

![all](https://user-images.githubusercontent.com/113134425/190159701-0cf957c9-e2a2-4186-ad49-df3a584aa2dd.png)

- Inglês:

![en](https://user-images.githubusercontent.com/113134425/190160949-38971d15-9b32-46da-b57f-2d9dfde3f86c.png)

- Português:

![pt](https://user-images.githubusercontent.com/113134425/190160973-5e9c2db1-0d26-4985-a01a-bd90118b9fef.png)

2022-09-14 15:08 UTC, GuilhermePedroMilani approved these changes
Pastas bem organizadas de acordo com as normas da arquitetura limpa.

2022-09-14 16:54 UTC, douglasWarren approved these changes

2022-09-14 17:25 UTC, CamileBarros requested changes
Realizar alterações de pastas acordadas em meet

2022-09-14 21:29 UTC, FelipeBortoliniWarren commented
Alterações feitas!

2022-09-15 11:40 UTC, CamileBarros approved these changes

2022-09-15 11:41 UTC, merged